### ISSUE TITLE
Refactor create_content to pass file directly to Hydra::Works::UploadFileToGenericFile

### ISSUE THREAD

**Issue by grosscol** [projecthydra-labs/curation_concerns#101]
The PR projecthydra-labs/hydra-works#154 will change the parameters accepted for the service objects that add files to generic files.  They will take anything that responds to `:read`.  They will make use of mime_type and original_name methods if available.

https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/actors/curation_concerns/generic_file_actor.rb#L54-64

**Comment by tampakis** [comment]
@grosscol, I'm happy to take over this issue unless if you've already taken a good stab at it.
