### ISSUE TITLE
Should GenericFile be generated into the host app?

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#124]
See also #112. Why would we generate [GenericFile](https://github.com/projecthydra-labs/curation_concerns/tree/master/curation_concerns-models/lib/generators/curation_concerns/models/templates/app/models/generic_file.rb) but not [GenericWork](https://github.com/projecthydra-labs/curation_concerns/tree/master/curation_concerns-models/lib/generators/curation_concerns/models/templates/app/models/generic_work.rb)? It could be that the intentions are different and that we don't expect the host application to treat them the same way.

**Comment by tampakis** [comment]
Unlike for works, currently there isn't a file generator in Curation Concerns. I don't think there is any functionality in the application to customize the file behavior and all works (whether they are catapults or generic works) expect GenericFiles to be attached to them. I think we can close this issue.

**Comment by jpstroop** [comment]
:+1:
