### ISSUE TITLE
Should CurationConcerns' Actors become concerns?

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#125]
(From a conversation I had with @tampakis late yesterday) #112 has us removing GenericWork (and #124 GenericFile, potentially) from the `curation_concerns:install` generator, but we'll still have hard-coded [Actor Classes](https://github.com/projecthydra-labs/curation_concerns/tree/master/curation_concerns-models/app/actors/curation_concerns) with those names (e.g. CurationConcerns::GenericWorkActor).

Should these actors become concerns (e.g. `app/actors/concerns/generic_work_actor_behavior.rb`) that the generator mixes into a generated Actor class? For example, if the user runs:

```
rails generate curation_concerns:work catapult
```

They get `app/models/actor.rb` and `app/actors/catapult_actor.rb`, which mixes in CurationConcerns::GenericWorkActorBehavior?

@tampakis, could add an explanation of the issue you were running into on #112 yesterday that sparked this conversation?

**Comment by jcoyne** [comment]
Yea, we should also generate an actor class for the work.  Worthwhile and curate did this I believe. I think `GenericWorkActorBehavior` should probably just be `WorkActorBehavior` and then generate:

```ruby
# app/actors/generic_work_actor.rb
class GenericWorkActor
  include CurationConcerns::WorkActorBehavior
end
```

**Comment by tampakis** [comment]
Yeah that would be better. Currently if someone wanted their work to actually be called "GenericWork" and ran `rails g curation_concerns:work GenericWork` it produces an actor class with a circular reference error.
```ruby
# app/actors/curation_concerns/generic_work_actor.rb
module CurationConcerns
  class GenericWorkActor < CurationConcerns::GenericWorkActor
  end
end
```

**Comment by jcoyne** [comment]
@tampakis in that case just rename `GenericWorkActor` to `WorkActor` and everything should just work.

**Comment by jpstroop** [comment]
:+1:

**Comment by jpstroop** [comment]
Wait, I would think that the generated class would be out of the CurationConcerns namespace, i.e.

```ruby
# app/actors/generic_work_actor.rb
class GenericWorkActor < CurationConcerns::GenericWorkActor
  include CurationConcerns::WorkActorBehavior
end
```

no? @jcoyne's pattern is using a  concern/mixin, @tampakis's is using a subclass.

**Comment by jcoyne** [comment]
I don't think the namespace matters much as long as it works.

**Comment by jpstroop** [comment]
But it'll solve the potential name collision problem.

And to be clear, you still want to subclass `CurationConcerns::GenericWorkActor` so that MyGeneratedActor `is_a?`  `CurationConcerns::GenericWorkActor`

**Comment by jcoyne** [comment]
@jpstroop it seems to me that the code would be clearer if the actor follow the same inheritance or mixin paradigm used by the work, so if `MyGeneratedActor < CurationConcerns::GenericWorkActor` then `MyGeneratedWork` should ` < CurationConcerns::GenericWork`.  Currently `MyGeneratedWork` is a subclass of `ActiveFedora::Base`

**Comment by tampakis** [comment]
I agree. However, currently having the GeneratedWork inherit from the GenericWork class causes the main app to think that the name of the work is "Generic Work" in the views - such as [here](https://github.com/projecthydra-labs/curation_concerns/blob/master/app/views/shared/_add_content.html.erb#L15) and [here](https://github.com/projecthydra-labs/curation_concerns/blob/master/app/views/curation_concerns/base/new.html.erb#L3)

**Comment by jpstroop** [comment]
Yeah, I was going to raise that on the call.

**Comment by jcoyne** [comment]
@tampakis how does include vs inherit change the behavior of human_readable_type?

**Comment by tampakis** [comment]
Inheriting from the GenericWork class makes that method return "Generic Work" rather than the name of the class generated (i.e. Catapult).


-------- Original message --------

**Comment by jcoyne** [comment]
@tampakis tampakis: that doesn't make any sense to me. Can you write a gist and show me?

**Comment by tampakis** [comment]
https://gist.github.com/tampakis/5af74b38ef926f808a1e

**Comment by jcoyne** [comment]
@tampakis Ah, this is just a consequence of how human_readable_type is implemented. It gets automatically set when `CurationConcerns::HumanReadableType` is included on GenericWork (see https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/human_readable_type.rb#L7) however, we as easily have it set that when it's inherited as well. Alternatively, have the generator add `self.human_readable_type = "Catapult"` to the generated class.
