### ISSUE TITLE
GenericFilesController copies parent access controls and disregards what is in the form

### ISSUE THREAD

**Issue by escowles** [projecthydra-labs/curation_concerns#129]

**Comment by jpstroop** [comment]
See the first item in #48. Make sure tests that gets moved over cover this.

**Comment by escowles** [comment]
@jpstroop -- I didn't find it initially, but after a little digging this can be resolved pretty easily, so I'll just wrap it up in #48.

**Comment by jpstroop** [comment]
:+1:
