### ISSUE TITLE
Refactor characterization controller tests

### ISSUE THREAD

**Issue by escowles** [projecthydra-labs/curation_concerns#132]
There are a couple of tests in spec/controllers/curation_concerns/generic_files_controller_spec.rb that are pending projecthydra-labs/hydra-works#89 -- when that is resolved and characterization is working, refactor the tests to demonstrate it.

See #48.

**Comment by mjgiarlo** [comment]
@terrellt I believe we decided to shift this over to v0.2?

**Comment by grosscol** [comment]
dependent on #139

**Comment by jcoyne** [comment]
@escowles can we close this?

**Comment by escowles** [comment]
Yep, looks like those pending tests are gone one way or the other.
