### ISSUE TITLE
Update generic_work to_s method and use it instead of title in the views

### ISSUE THREAD

**Issue by tampakis** [projecthydra-labs/curation_concerns#136]
Update 'to_s' method in [GenericWorkBehavior](https://github.com/projecthydra-labs/curation_concerns/blob/e1bb116e14ed5417a6950fb8ff1decbea0f57714/curation_concerns-models/app/models/concerns/curation_concerns/generic_work_behavior.rb#L26) so it doesn't assume the title attribute is present. Make it more similar to the to_s method in [serializers.rb](https://github.com/projecthydra-labs/curation_concerns/blob/e1bb116e14ed5417a6950fb8ff1decbea0f57714/curation_concerns-models/app/models/concerns/curation_concerns/serializers.rb)

Use the to_s instead when rendering the title in the views.

**Comment by mjgiarlo** [comment]
There is code in Sufia to use a filename to auto-populate if title is not otherwise set by the user.  This code could be used to do the same for works, though that doesn't help for 0-file works.

**Comment by tampakis** [comment]
Related to #235

**Comment by tampakis** [comment]
It looks like all work-related views use the [curation_concern_page_title](https://github.com/projecthydra-labs/curation_concerns/blob/master/app/helpers/curation_concerns/title_helper.rb#L6), so I think this is the only view-related code that needs to use the new 'to_s' method.

**Comment by tampakis** [comment]
Closed by #266.
