### ISSUE TITLE
Move characterization down to Hydra::Works

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#139]
And rely on it. Reciprocal in hydra-works: projecthydra-labs/hydra-works#89.  Update the [code shredding document](https://docs.google.com/spreadsheets/d/1uyCtjcBeSr0rWu4AieVplygrhWVTwwR0v6Itq6PBeA0/edit#gid=295544419) when complete.

**Comment by jpstroop** [comment]
@grosscol Any updates here? It would be great if we could get 0.2 released before HydraConnect.

**Comment by grosscol** [comment]
@jpstroop Yes.  I'm moving the ch13n to work on top of projecthydra-labs/hydra-works#209 which is currently waiting on https://groups.google.com/forum/?hl=en#!topic/hydra-tech/KWH-bUo1F3s

**Comment by jpstroop** [comment]
@grosscol thanks! I apologize, I'd missed that thread.
