### ISSUE TITLE
Move CurationConcerns::DefaultMetadata to Hydra::Works

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#140]
([This](https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/with_basic_metadata.rb)) And rely on it. Update the [code shredding document](https://docs.google.com/spreadsheets/d/1uyCtjcBeSr0rWu4AieVplygrhWVTwwR0v6Itq6PBeA0/edit#gid=295544419) when complete.

Reciprocal issue in hydra-works: projecthydra-labs/hydra-works#91

**Comment by jpstroop** [comment]
Consensus on 8/5 was to leave this where it is.

**Comment by mjgiarlo** [comment]
#wontfix because 1) already working in CurationConcerns and 2) no strong stated need to have this pushed down.
