### ISSUE TITLE
Move CurationConcerns::FullTextExtractionService to Hydra::Works

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#141]
Reciprocal issue: projecthydra-labs/hydra-works#95. (see [this comment](https://github.com/projecthydra-labs/hydra-works/issues/95#issuecomment-128359762)). The service call and indexing should stay here, but extraction should move down to H::W.

**Comment by mjgiarlo** [comment]
This work in hydra-works has been merged: https://github.com/projecthydra-labs/hydra-works/pull/195

Thanks, @blancoj

**Comment by mjgiarlo** [comment]
@jcoyne is taking this.

**Comment by tampakis** [comment]
Closed by https://github.com/projecthydra-labs/curation_concerns/pull/280
