### ISSUE TITLE
Move Indexing to Hydra::Works

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#142]
Reciprocal issue in Hydra::Works is part 1 of projecthydra-labs/hydra-works#95. Update the [code shredding document](https://docs.google.com/spreadsheets/d/1uyCtjcBeSr0rWu4AieVplygrhWVTwwR0v6Itq6PBeA0/edit#gid=295544419) when complete.

**Comment by jpstroop** [comment]
Decision from call on 8/5 was (I believe) that Hydra::Works and CurationConcerns should also have an indexer (overriding Hydra::Works' indexer (??)), which should render this wontfix.

@jcoyne, @terrellt: care to weigh in before I close?

**Comment by jcoyne** [comment]
Sounds right to me. The `CurationConcerns::GenericWorkIndexingService` only indexes member_ids as generic_file_ids.  See: https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/services/curation_concerns/generic_work_indexing_service.rb#L10 This is more efficient than loading all the members and categorizing into child_collections and child_objects as the Hydra::Works indexer would likely have to do.
