### ISSUE TITLE
Pull Single Use Links down from sufia-core

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#146]
Per the [code shredding halftime review](https://docs.google.com/document/d/1XWW5u2qflcpqAZDf0dtDYBD22Qqkd7L5rEQuisHvgX4/edit#heading=h.9yg4m11beddd).

___TODO:___ Reciprocal issue in sufia-core: projecthydra-labs/sufia-core#___

**Comment by mjgiarlo** [comment]
Review this gem which extracts single-use links out of Sufia:

https://github.com/projecthydra-labs/single_use_links

It might be nice to have this as a separate gem and the work has already been started here.

**Comment by cam156** [comment]
@mjgiarlo  That gem seems to be a stub for a future gem (there is no real code).  Seems like that is above and beyond this ticket.

**Comment by mjgiarlo** [comment]
Oh, hey, whaddya know. I thought @cbeer extracted single-use links at some point, but that's not it. Maybe it's all a figment of my imagination! :pill:  Thanks for reviewing that gem, @cam156

**Comment by jcoyne** [comment]
@cam156 can this close now?

**Comment by grosscol** [comment]
Closed by #151
