### ISSUE TITLE
Implement sufia-like authority functionality using questioning_authority

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#147]
This came from the [code shredding halftime review](https://docs.google.com/document/d/1XWW5u2qflcpqAZDf0dtDYBD22Qqkd7L5rEQuisHvgX4/edit#heading=h.9yg4m11beddd).

___TODO:___ Reciprocal issue in sufia-core: projecthydra-labs/sufia-core#___

**Comment by mjgiarlo** [comment]
:+1: but rather than pulling in Sufia's authorities implementation (which pre-dates Questioning Authority), consider using QA. Also have a look at LinkedVocabs or Oargun, which I don't understand fully but which may bring more RDF-iness.

**Comment by terrellt** [comment]
Are authorities in Sufia actual authorities, or just type-ahead?

**Comment by mjgiarlo** [comment]
We harvest the URIs and labels into the DB but users only ever see the labels. So, mostly type-ahead with a local cache of URIs for reverse lookup.

**Comment by terrellt** [comment]
But there's no restriction to only use labels that come from the type-ahead?

**Comment by mjgiarlo** [comment]
Only labels come back from the type-ahead at the moment.  It *could* easily return URIs too.

**Comment by jpstroop** [comment]
@mjgiarlo I updated the description to state that we should bring in QA instead, but haven't made a reciprocal issue in sufia-core because I'm not sure how that fits into the plans for sufia.

**Comment by mjgiarlo** [comment]
:ok: I'd love to s/bespoke/QA/ in Sufia but given all that's changing now, I think it's best to backburner that. So :+1: to not pushing that now.

**Comment by mjgiarlo** [comment]
Sufia currently links four vocabularies to four fields, FYI: Geonames to Location, LCSH to Subject, Lexvo to Language, and LC Genres to Keyword/Tag.

**Comment by njaffer** [comment]
Should we look at linking all four vocabularies for Curation Concern as well?

**Comment by mjgiarlo** [comment]
Good question, @njaffer. I defer to @jpstroop and @jcoyne who are both building apps based directly on CC right now.

**Comment by jcoyne** [comment]
I don't care about this feature at the moment. Having worked on linked data hydra-head, I think this is probably a bigger piece of work than we want to bite off right now.

**Comment by mjgiarlo** [comment]
What say you, @jpstroop? Do you want this in 0.2 or can it be deferred?

**Comment by jpstroop** [comment]
+1 to defer. Closing in favor of a new ticket that can be written when a clearer use case surfaces.
