### ISSUE TITLE
Collection show view should have a "remove from collection" action for each of its generic files

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#148]
Within Sufia in the Show view of a Collection you see details/metadata (title, description, thumbnail) about the collection and then see, below it, search results for the items in the collection.  Those items look like search results from the dashboard and have full pagination, query (search within collection), etc.  Each result in the list of collection contents also has a button/action to "remove item from collection"

Pull those views into curation_concerns.  This will add:

 * embedded search within collection
 * “remove from collection” 
 * etc.

Per the [code shredding halftime review](https://docs.google.com/document/d/1XWW5u2qflcpqAZDf0dtDYBD22Qqkd7L5rEQuisHvgX4/edit#heading=h.9yg4m11beddd).

___TODO:___ Reciprocal issues in sufia-core: projecthydra-labs/sufia-core#___

**Comment by terrellt** [comment]
Removed milestone as we don't have a clear understanding now of what these customizations are.

**Comment by flyingzumwalt** [comment]
Within Sufia in the Show view of a Collection you see details/metadata (title, description, thumbnail) about the collection and then see, below it, search results for the items in the collection.  Those items look like search results from the dashboard and have full pagination, query (search within collection), etc.  Each result in the list of collection contents also has a button/action to "remove item from collection"

**Comment by cam156** [comment]
@flyingzumwalt It looks like all the functionality is there with the exception of the remove from collection option.  Is that correct?
![screen shot 2015-09-01 at 2 42 10 pm](https://cloud.githubusercontent.com/assets/1599081/9613149/afda5720-50b7-11e5-8754-91222343e5b3.png)

**Comment by flyingzumwalt** [comment]
I'm not sure.  @jpstroop created the ticket based on my old notes in google
docs.  I just filled in clearer details about what we want.  If the
functionality is already there, then it's fine to close the ticket.

**Comment by jpstroop** [comment]
Don't have time to spin this up at the moment, but that looks like the case from @cam156 screenshot

**Comment by terrellt** [comment]
Spun it up and that's true. I'll edit the title for this ticket.
