### ISSUE TITLE
Merge relevant Sufia functionality into curation_concerns

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/curation_concerns#15]
see PR  #12 
refs #4 and #5

**Comment by jpstroop** [comment]
Progess on tests: https://docs.google.com/document/d/1cYXayPwu47OPrAoVz6AzoI4R_y4Rg0NCvgXW0Cr8cG8/edit#heading=h.qwe05wxyz9ri

**Comment by jpstroop** [comment]
Closed by 10f702b5a212cd07273e81d64be429dc396dc9c6
