### ISSUE TITLE
Remove dependency on sufia-models 

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/curation_concerns#17]
This will allow us to make sufia depend on curation_concerns.

 - [x] move all GenericFile model-level code from sufia-models into curaiton_concerns (or hydra-works)
 - [x] move all Collection model-level code from sufia-models into curaiton_concerns (or hydra-works)

**Comment by jpstroop** [comment]
Details here: https://docs.google.com/document/d/1cYXayPwu47OPrAoVz6AzoI4R_y4Rg0NCvgXW0Cr8cG8/edit#heading=h.qwe05wxyz9ri

**Comment by jpstroop** [comment]
This should have been close w/ 3f583d0d374693c9ef39abd242e48e9262b0f7d8
