### ISSUE TITLE
Remove use of .add_file in spec

### ISSUE THREAD

**Issue by grosscol** [projecthydra-labs/curation_concerns#172]
@cam156 pointed out that this method comes from hydra-head.  The function there is deprecated and slated for removal in hydra-head 10.0.  Should probably be using HydraWorks AddFileToGenericFile service.

spec/models/checksum_audit_log_spec.rb
spec/models/generic_file_spec.rb
spec/services/repository_audit_service_spec.rb

**Comment by jcoyne** [comment]
Is this done?

**Comment by grosscol** [comment]
I thought this was being fixed in #151.  Although I'm still seeing it in:
spec/views/single_use_links/new_download.html.erb_spec.rb
spec/views/single_use_links_viewer/show.html.erb_spec.rb

**Comment by mjgiarlo** [comment]
This looks like it's assigned to @cam156

**Comment by cam156** [comment]
It looks like it was done, until more got introduced by me...

**Comment by cam156** [comment]
This seems to be complete
