### ISSUE TITLE
Remove dependency on Blacklight

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/curation_concerns#18]
- [ ] remove anything that relies on Blacklight or CatalogController
 - [ ] rewrite the install generator to allow adopters to get Devise, etc. without installing blacklight and running blacklight generator.

**Comment by flyingzumwalt** [comment]
Note: Can't remove blacklight from dependency tree because hydra-access-controls and hydra-collections both depend on it.  Still aiming to remove any code from curation_concerns that relies on blacklight and aiming to remove need for blacklight installer if possible.

**Comment by tampakis** [comment]
Blacklight is directly used within Curation Concerns in retrieving works and collections from Solr. Essentially all of the Blacklight generator would have to be copied into the Curation Concerns generator to maintain current functionality.

**Comment by flyingzumwalt** [comment]
Not worth the effort.
