### ISSUE TITLE
audio/video derivatives have bogus use predicates

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#188]
Two potential solutions:
1) Don't store derivatives in the repository. Store directly on disk.
2) Update `directly_contains_one` to scope by use predicate and mime-type.

**Comment by jpstroop** [comment]
I'm :-1: to not storing derivatives in the repository, or at least not having the option to do so. If I'm reading [this](https://github.com/projecthydra-labs/curation_concerns/blob/263f2966ba1b4f5ca3e5ad1cec7013b858e5bd4d/curation_concerns-models/app/models/concerns/curation_concerns/generic_file/derivatives.rb#L7) correctly, I _think_ I still do, right? (by changing back to `Hydra::Derivatives::PersistOutputFileService`) Or is that going to break other assumptions elsewhere in CurationConcerns going forward?

Use case: We have JP2 derivatives of our TIFF images. The parameters for making the JP2 varies from object to object and will be chosen by a human at ingest time, so these derivatives are curated and couldn't simply be regenerated. We need to be able to preserve and manage these files just like any other object in the repo. (ping @eliotjordan @tampakis)

**Comment by jcoyne** [comment]
@jpstroop the PR that fixes this (#194) just changes the default to the filesystem.  It is still possible to override it.  In the future it might be optimal to have a way of configuring how each kind of derivative is persisted.

**Comment by jcoyne** [comment]
@jpstroop also, thanks for providing that use case, that's very helpful in illustrating your point.
