### ISSUE TITLE
Need to clarify Assumptions about namespacing of works and GenericFiles within controllers, routing, etc.

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/curation_concerns#20]
The current assumptions are unclear and confusing.  We need to fix that.

### What's not clear

given a request to `/concerns/my_work_type`, 
* what controller will it load? 
* what model will it use to load @curation_concern?

given a request to `/concerns/generic_files`, 
* what controller will it load?
*what model will it use to load @curation_concern?

### What I thought was happening:

It looks like the curaiton_concerns:work generator puts the model in the root namespace (ie. MyWorkType instead of CurationConcerns::MyWorkType)

### What I ran into:

Based on that, I thought that `CurationConcerns::GenericFilesController` should load a `GenericFile` as the @curation_concern, not `CurationConcers::GenericFile`.     

THE PROBLEM was that when I this all of the routes generated by views tried to route to `/generic_files/…` intstead of `/concerns/generic_files/…` *I don't know why this happens with `GenericFiles` but not with generated works*.

NOTE: This might be because GenericWorksControllers use set_curation_concern_type but GenericFilesController isn’t using it...

**Comment by terrellt** [comment]
@flyingzumwalt I think this was fixed a few weeks ago by @tampakis. Can you confirm @tampakis?

**Comment by tampakis** [comment]
Both GenericFile and any generated work type use the `/concerns` namespace now. I'm not sure exactly where the routing for generic files got fixed, but [route specs](https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/routing/route_spec.rb) for both files and works were added since this issue was opened.
