### ISSUE TITLE
Do we want image dimension indexed?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#202]
Originally added in: https://github.com/projecthydra-labs/curation_concerns/commit/a0cf0739db3dd32d97951bfca19b2bb645e6125a

presently living here: https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/generic_file_behavior.rb#L35-L36

I think we can either 1) remove or 2) move to GenericFileIndexer	but it shouldn't remain where it is.

**Comment by mjgiarlo** [comment]
:+1: to GenericFileIndexer.

**Comment by jpstroop** [comment]
I can imagine not wanting to pull this info out more than once, so if there are any use cases around needing to know the size or aspect ratio of an image, then I tend to agree that it should get moved rather than pulled.
