### ISSUE TITLE
Remove GenericFile::Export

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#205]
https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/generic_file/export.rb

This is used by sufia, but not CurationConcerns. Should we remove it? 

/cc @mjgiarlo @cam156

**Comment by mjgiarlo** [comment]
I wrote that module, largely copying and adapting a bunch of it from Blacklight, and I hate it with a passion.  That said, some people actually use it.  I'm fine with it being dumped in CC as long as it sticks around and works in Sufia.
