### ISSUE TITLE
Rely on hydra-works GenericWorkBehavior

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/curation_concerns#22]
- [ ] Make CurationConcerns::GenericWorkBehavior rely on Works::GenericWorkBehavior
 - [ ] Remove overlapping code that came from Sufia & Worthwhile (ie. associations between generic_files and generic_works

This is blocked by projecthydra-labs/hydra-works#128
which was blocked by projecthydra-labs/activefedora-aggregation#39

ref #14

**Comment by terrellt** [comment]
Is this closable?
