### ISSUE TITLE
ActiveFedora::Associations::ContainerProxy#delete hangs on Fedora 4.3.0

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#234]
Caused by this line: https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/actors/curation_concerns/work_actor_behavior.rb#L45

in active-fedora-9.3.0/lib/active_fedora/associations/collection_association.rb:362 (delete_or_destroy)

Looks like its Hydra::PCDM::Validators::AncestorValidator
/Users/justin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hydra-pcdm-0.1.0/lib/hydra/pcdm/validators/ancestor_validator.rb

running `rspec spec/actors/curation_concerns/work_actor_spec.rb:188`

**Comment by jcoyne** [comment]
Using active-fedora-9.3.0, it is getting in a loop where it is retrieving the GenericWork over and over again.

**Comment by terrellt** [comment]
Closed by https://github.com/projecthydra/active_fedora/pull/888
