### ISSUE TITLE
Use to_s for generic_file title in show views.

### ISSUE THREAD

**Issue by tampakis** [projecthydra-labs/curation_concerns#235]
Generic_file show pages call `generic_file.title.first` which will fail if the generic_file title isn't set. Use the to_s method instead.

**Comment by jcoyne** [comment]
It shod display the label (file name) if a title isn't set

**Comment by tampakis** [comment]
Where? I got a nil error when I forgot to enter set a filename from this partial: https://github.com/projecthydra-labs/curation_concerns/blob/master/app/views/curation_concerns/generic_files/media_display/_image.html.erb#L4

**Comment by jcoyne** [comment]
It should be using this: https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/solr_document_behavior.rb#L3  That partial may need to be updated to use it.
