### ISSUE TITLE
  Change "Generic File" to just "File" in UI

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#257]
The term "Generic File" isn't really meaningful to end-users and isn't used consistently on the rest of the page, so just say "File"

**ROUTE**
/concern/container/ID/generic_files/new

<img width="549" alt="wustl 066 - generic file wording in ui" src="https://cloud.githubusercontent.com/assets/3064318/9531124/c40a59f8-4cc9-11e5-9d4f-8566e068b9c4.png">

**Comment by grosscol** [comment]
Should be File Set now instead of Generic File

**Comment by grosscol** [comment]
Should be File Set now instead of Generic File
