### ISSUE TITLE
Remove Batch and generic_file.batch

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/curation_concerns#27]
Example: GenericFileActor#create_metadata takes both _batch_id_ and _work_id_. It's not clear what will be done with each.  The tests and the surrounding code are not clear about it either.

**Comment by flyingzumwalt** [comment]
also see #29

**Comment by jpstroop** [comment]
Per #145, Batches (to be renamed) are coming down here from sufia-core.
