### ISSUE TITLE
Double bread_crumb_on_rails

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/curation_concerns#289]
I get errors when I try to generate the test app
The gemspec at /Users/cam156/curation_concerns/curation_concerns.gemspec is not valid. The validation error was
```
duplicate dependency on breadcrumbs_on_rails (~> 2.3.0), (~> 2.3.0) use:
    add_runtime_dependency 'breadcrumbs_on_rails', '~> 2.3.0', '~> 2.3.0'
```
This commit: https://github.com/projecthydra-labs/curation_concerns/commit/3cf7912c0c654b61f88fcd4d6c4daa2c9bad3189 added it a second time.
It should be removed.

**Comment by jcoyne** [comment]
Oops. Sorry
