### ISSUE TITLE
Should the batch model come over from sufia-models?

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#29]
[Code shredding doc](https://docs.google.com/spreadsheets/d/1uyCtjcBeSr0rWu4AieVplygrhWVTwwR0v6Itq6PBeA0/edit#gid=295544419) mentions `Batch`___es___, but not [Batch](https://github.com/projecthydra-labs/sufia-core/blob/master/sufia-models/app/models/batch.rb) or the relevant controller, etc. There's also [this rake task](https://github.com/projecthydra-labs/sufia-core/blob/master/sufia-models/lib/tasks/batch_cleanup.rake), and a copy of [this spec](https://github.com/projecthydra/sufia/blob/eb714cb91f4ecd49dec67b0e9996dc3d4e918f1a/spec/jobs/batch_update_job_spec.rb) (which has everything marked pending in the version in this repo).

**Comment by flyingzumwalt** [comment]
I have a hunch that there is still use for knowing which files were uploaded together, as opposed to which files belong to the same work.  If there is still use for the former, then we should include Batch.  Maybe check with @cam156 @awead and @mjgiarlo to see if they think Batch is still necessary.

**Comment by flyingzumwalt** [comment]
Related to #27

**Comment by jpstroop** [comment]
Decided on call w/ Matt on 7/6 that all notions of a Batch should be moved to sufia-core.

**Comment by mjgiarlo** [comment]
:+1: 

I believe a couple of us came to the same conclusion independently a couple weeks ago while brainstorming, so this is good to hear!
