### ISSUE TITLE
fits test fail locally.  What did I do wrong?

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/curation_concerns#291]
To get spec/models/fits_datastream_spec.rb to run I had to manually run
```
cp curation_concerns-models/lib/generators/curation_concerns/models/templates/config/solrconfig.xml jetty/solr/test-core/conf/
cp curation_concerns-models/lib/generators/curation_concerns/models/templates/config/solrconfig.xml jetty/solr/development-core/
```
Seems like there should be a rake task or something.

I ran rake curation_concerns:jetty:config and that did not fix it for me.

**Comment by tampakis** [comment]
This is because the full text extractor isn't getting loaded anymore into Solr. Once https://github.com/projecthydra-labs/hydra-works/pull/204 is merged, I'll submit a PR to get that working again.

**Comment by cam156** [comment]
@tampakis Thanks!  I do not think this is a new issue, as I have had failing extracted text tests since I started working on the project a few weeks ago.  I just spent the time to track it down today.

**Comment by tampakis** [comment]
Also, I run `rake jetty:config` instead of `rake curation_concerns:jetty:config` which will also copy those files into jetty.

**Comment by cam156** [comment]
@tampakis Thanks!
