### ISSUE TITLE
Remove LinkedResource

### ISSUE THREAD

**Issue by tampakis** [projecthydra-labs/curation_concerns#30]
It's unclear if and how much of LinkedResource should live in curation_concerns. The [controller](https://github.com/projecthydra-labs/worthwhile/blob/b89d24d82904633e040468ce0d57a7fa7b9cbbb6/app/controllers/curation_concern/linked_resources_controller.rb) was removed, but the [routes](https://github.com/projecthydra-labs/curation_concerns/blob/master/lib/curation_concerns/rails/routes.rb#L16-L17) are still there as well as some [other behavior](https://github.com/projecthydra-labs/curation_concerns/blob/3e3271057a0be15210bb19502daece3a4a31d368/curation_concerns-models/app/actors/curation_concerns/generic_work_actor.rb#L57-L76).

**Comment by jpstroop** [comment]
This was impl in a very F3-specific way and it would likely be easier to start from scratch.
