### ISSUE TITLE
Error with Rails Class Reloading 

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/curation_concerns#305]
When you have a running copy of a Rails app that uses curation_concerns, if you edit any class (models, controllers, routes, etc), you get an error page on refresh that complains:
`uninitialized constant Hydra::PCDM::ObjectBehavior::RDFVocabularies`

**Comment by jcoyne** [comment]
This is because you are using an out of date version of curation_concerns/hydra-works/pcdm gems.
