### ISSUE TITLE
If FullTextExtract fails, the whole characterization fails.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#322]
Because it never gets to save.

**Comment by jcoyne** [comment]
Should full text extraction be its own job?

https://github.com/projecthydra-labs/curation_concerns/blob/36c7788369610a4e71c0864d221c409cd95d6b96/curation_concerns-models/app/services/curation_concerns/characterization_service.rb#L18

**Comment by mjgiarlo** [comment]
:+1: to disentangling these and handling errors more gracefully.

**Comment by grosscol** [comment]
I was just looking at this myself.  I don't see how the full text extraction affects characterization.

**Comment by jpstroop** [comment]
Can't look into the details now, but I agree w/ @mjgiarlo, they should be disentangled if they are, and unless you're going to run into problems with two jobs running on the same file (and stepping on each other), I think a separate jobs seems logical.

**Comment by jcoyne** [comment]
Here's a specific error. It's tried to upload a TIFF and solr gives this error:
```
Solr Extract service was unsuccessful. 'http://localhost:8080/hydra/update/extract?extractOnly=true&wt=json&extractFormat=text' returned code 500 for 5138jd86g {"error":{"msg":"java.lang.NoClassDefFoundError: org/apache/tika/mime/MimeTypeException","trace":"java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/tika/mime/MimeTypeException\n\tat org.apache.solr.servlet.SolrDispatchFilter.sendError(SolrDispatchFilter.java:793)\n\tat 
```

Thus characterization was not saved and derivatives not run.
