### ISSUE TITLE
Bucketed Disk Derivatives - Question

### ISSUE THREAD

**Issue by terrellt** [projecthydra-labs/curation_concerns#331]
With the current strategy of persisting derivatives to disk there's going to be a LOT of folders created in the configured derivatives folder. We've implemented a pair-tree algorithm for Plum at https://github.com/pulibrary/plum/pull/69 - should we just implement it here instead?

**Comment by jcoyne** [comment]
Yep. :+1:

**Comment by terrellt** [comment]
Alright, should have a PR in the next hour or so.
