### ISSUE TITLE
Checksum Audit Log is not working

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/curation_concerns#34]
All of the relevant specs are marked pending right now.
`./spec/jobs/audit_job_spec.rb`
Looks like it's blocked by versioning behavior that isn't working?

**Comment by flyingzumwalt** [comment]
Is this resolved?

**Comment by cam156** [comment]
@flyingzumwalt there are no pending test in that file.  I believe it is complete.
