### ISSUE TITLE
Move Sufia controller specs

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#36]
* [ ] https://github.com/projecthydra-labs/sufia-core/blob/master/spec/controllers/curation_concern/generic_works_controller_spec.rb
  * [ ] https://github.com/projecthydra-labs/sufia-core/blob/master/spec/controllers/curation_concern/permissions_controller_spec.rb

**Comment by kevinreiss** [comment]
These are already moved into this repo and pass. closing.
