### ISSUE TITLE
Use VirusCheck from Hydra::Works (was: Decide if VirusCheck belongs in CurationConcerns or Sufia)

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/curation_concerns#37]
With this comes dependency on ClamAV.

**Comment by jpstroop** [comment]
Yeah...that's a tricky one. I think you can justify putting just about everywhere. In some ways this is like making derivatives, characterization, etc., so I wonder if Hydra::Works is the place?

**Comment by jpstroop** [comment]
In fact...that's where we have it in the Code Shredding doc

**Comment by escowles** [comment]
:+1: for CurationConcerns or lower

**Comment by jcoyne** [comment]
While the Virus check requires clamAV, It is not a hard dependency.  In the 6.0 version of sufia, if you choose not to use Virus checking, you don't have to install clamAV.

**Comment by jpstroop** [comment]
I still tend to think it belongs in Hydra::Works. In the [original code shredding doc](https://docs.google.com/spreadsheets/d/1uyCtjcBeSr0rWu4AieVplygrhWVTwwR0v6Itq6PBeA0/edit#gid=295544419) we have VirusCheck, derivatives, characterization, full text indexing ultimately landing there (and I'd like to add [tesseract support](https://github.com/meh/ruby-tesseract-ocr), eventually), even though some or all of those are still temporarily living in CurationConcerns.

**Comment by escowles** [comment]
As long as it's not a hard dependency, Hydra::Works sounds like the right place to me too.

**Comment by jpstroop** [comment]
Update the [code shredding document](https://docs.google.com/spreadsheets/d/1uyCtjcBeSr0rWu4AieVplygrhWVTwwR0v6Itq6PBeA0/edit#gid=295544419) when complete.
