### ISSUE TITLE
Refactor "pending #89" characterization specs

### ISSUE THREAD

**Issue by grosscol** [projecthydra-labs/curation_concerns#373]
Resolve both `skip 'pending hydra-works#89'` in the file_sets_controller_spec. 

https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/controllers/curation_concerns/file_sets_controller_spec.rb

**Comment by njaffer** [comment]
@grosscol I will work on this one

**Comment by mjgiarlo** [comment]
@njaffer OK, we concluded that changing the `expect` to `allow` in the `before` block would be good.

**Comment by njaffer** [comment]
@mjgiarlo ok I will update in both places (models and controllers specs)
