### ISSUE TITLE
FYI: Sufia can register event jobs in CurationConcerns.config, but none are set by default in CurationConcerns

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/curation_concerns#38]
Sufia sets up a bunch of event jobs like content_deposit_event in `config/initializers/sufia_events.rb`.  These mostly add things to a user's activity stream, which is a sufia-ir feature.

curation_concerns _does_ call those events (from GenericFileActor and GenericWorkActor) if they're registered, but it does not register any of its own.

**Comment by jcoyne** [comment]
Nothing to do here.
