### ISSUE TITLE
Representative Work Predicate

### ISSUE THREAD

**Issue by tpendragon** [projecthydra-labs/curation_concerns#398]
Currently it's using http://opaquenamespace.org/ns/hydra/representative, which doesn't resolve - is there an existing one we should use instead, or do we need to mint one (potentially at ON)?

**Comment by escowles** [comment]
I don't know any existing predicates that are a good fit -- minting on at ON seems like a good idea to me.

**Comment by kestlund** [comment]
I don't know any good fits either. I also think the definition there is part of why that one is a bit tricky.  Is there a particular schema that you are using for defining what is a representative work even if it doesn't have a full ontology.

Have you talked to @wickr about using ON?  We have this same community problem that we had we we minted opaquenmamespace.org, but I'm not sure it really is the answer.  Where do we put these sort of things?

**Comment by wickr** [comment]
I'm definitely open to using ON.

Is http://purl.org/spar/fabio/hasRepresentation  too FRBR-centric to use?  http://www.essepuntato.it/lode/http://purl.org/spar/fabio#d4e287

**Comment by jcoyne** [comment]
I wonder if http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Media is a good choice.  I also wonder if we should split representative from thumbnail (http://schema.org/thumbnail perhaps)?
