### ISSUE TITLE
Test Fits Related Specs in CI

### ISSUE THREAD

**Issue by kevinreiss** [projecthydra-labs/curation_concerns#40]
Should we do this? Need to create a rake task to execute set-up.

**Comment by jpstroop** [comment]
We have a rake task in pulstore:

* https://github.com/pulibrary/pul-store/blob/development/lib/tasks/install_fits.rb
* https://github.com/pulibrary/pul-store/blob/development/lib/tasks/fits.rake

After which, [this line](https://github.com/projecthydra-labs/curation_concerns/blob/remove_sufia/spec/spec_helper.rb#L17) can go.

**Comment by kevinreiss** [comment]
@jpstroop I think that once https://github.com/projecthydra-labs/curation_concerns/issues/46 is resolved we will no longer actually need the $in_travis flag in this gem. All the code that needs exemption will be moved over to hydra-works.

**Comment by jpstroop** [comment]
That sounds right. Close this then?

**Comment by kevinreiss** [comment]
Let's leave it open until #46 closes just in case.
