### ISSUE TITLE
Mime-type is being returned as an array

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra-labs/curation_concerns#449]
The current version of SolrDocumentBehavior returns an array (rather an a single value) for the mime type https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/solr_document_behavior.rb#L115:

```
    def mime_type
      self[Solrizer.solr_name('mime_type', :stored_sortable)]
    end
```

This causes several methods in HydraWorks to work incorrectly. For example method to detect if a mime type is an office document here https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/models/concerns/file_set/mime_types.rb#L22 expects `mime_type` to be a single string like `"text/rtf"` rather than `["text/rtf"]`

I think we should update the code in Curation Concerns to return a single value rather than an array to preserve the semantics that this method used to provide. Otherwise we will need to update everyplace where mime_type is accessed.

**Comment by jcoyne** [comment]
:+1: sounds good. I don't ever want a file to have more than one mime type.

**Comment by grosscol** [comment]
Reality really doesn't care about our desires.  You can have a file that is valid for multiple mime-types.  However, for our purposes not handling those (hopefully exceedingly rare) cases is probably a better route.

**Comment by jcoyne** [comment]
Here's what I'm seeing prior to this change:

```
resp = CatalogController.new.repository.find('zg64tm30p')
resp.fetch('response').fetch('docs').first.fetch('mime_type_ssi')
=> "image/jpeg"
```

It's a scalar, not an array.

**Comment by hectorcorrea** [comment]
Nevermind. Problem was in some of the Sufia code that was using this wrong.
