### ISSUE TITLE
IngestLocalFile job attempts to use non-existant method original_filename

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#456]
```
    NoMethodError:
       undefined method `original_filename' for #<File:spec/mock_upload_directory/world.png>
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-02e5526e70bf/curation_concerns-models/app/actors/curation_concerns/file_set_actor.rb:114:in `copy_file_to_working_directory'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-02e5526e70bf/curation_concerns-models/app/actors/curation_concerns/file_set_actor.rb:59:in `create_content'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-02e5526e70bf/curation_concerns-models/app/jobs/ingest_local_file_job.rb:21:in `perform'
```

**Comment by jcoyne** [comment]
the local File objects don't have original_filename. Only `HTTP::UploadedFile`s have that.

**Comment by jcoyne** [comment]
I think we can just use `FileSet#label` in lieu of `original_filename` on 114

**Comment by tpendragon** [comment]
I believe the label is set using original filename. Ran into this implementing browse everything.

**Comment by jcoyne** [comment]
@tpendragon label is *sometimes* set using original_filename.  Here is a case where it isn't https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/jobs/ingest_local_file_job.rb#L15

**Comment by grosscol** [comment]
Does this go all the way back to add file to fileset service from hydra works?  That service attempted to use the original_filename if available, but would try other values if the original_filename method was not available.

**Comment by jcoyne** [comment]
@grosscol I don't think so.  I think this was just not being mindful about what the interface is or designing a good interface in the first place.

**Comment by grosscol** [comment]
@jcoyne I see.  The file set actor is expecting a `ActionDigest::HTTP::UploadedFile` or `Tempfile`.  It's assuming that file will have an original_filename prior to being ingested.  The FileSetActor can be refactored to accept File and the label and title setting can be done as part of IngestFileJob where the file gets wrapped in a Hydra::Derivatives::IoDecorator, and original_name gets set.

Either the file_set label and title have to be done after IngestFileJob, or within IngestFileJob.  I'm going to write it into IngestFileJob.  It is similar to what the CreateDerivativesJob does.

**Comment by jcoyne** [comment]
Colin, the problem isn't that label isn't set. It's that it isn't used in file_set_actor.rb:114
