### ISSUE TITLE
Generated models are not in the curation_concerns namespace.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#463]
When we generate a model it is in the root namespace (i.e. `GenericWork`).  However the controller we generate is in the `CurationConcerns` namespace (i.e. `CurationConcerns::GenericWorksController`).

We should do something to match these into the same namespace.  I propose we have the models generate into the CurationConcerns ns.

**Comment by grosscol** [comment]
I agree we should have the models and controllers in the same namespace.  Would we like to allow generating the models ect in the project's namespace and just keeping the behaviors references in the CC namespace?

**Comment by jcoyne** [comment]
Since all the views the controllers render are in `app/views/curation_concerns/base/*`, I think it's least suprising to make them curation_concerns controllers.  This also differentiates the controllers tasked with repository CRUD from the other controllers.

**Comment by grosscol** [comment]
I see.  That does make a great deal more sense.

**Comment by jcoyne** [comment]
wontfix.  We changed the models to have the correct route keys though.
