### ISSUE TITLE
UploadSet should have a depositor property

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#468]
https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/upload_set_behavior.rb#L10

Use `RDF::Vocab::MARCRelators.dpt` as the predicate

**Comment by hectorcorrea** [comment]
Per @jcoyne: we should also investigate if `creator` is still needed. Not sure they (`creator` vs `depositor`) will ever be different.

**Comment by hectorcorrea** [comment]
@mjgiarlo @jcoyne I get the impression that the `UploadSet.creator` is user defined (see https://github.com/projecthydra-labs/curation_concerns/blob/master/app/views/upload_sets/_metadata.html.erb#L35) 

Not sure if this helps to answer the question on whether they will ever be different. Thoughts?

**Comment by mjgiarlo** [comment]
@hectorcorrea The UploadSet **form**'s creator value is user defined, and is applied to all things in the UploadSet, not the UploadSet itself. UploadSets should not have descriptive metadata. I just spun up Sufia (6.x) master and deposited a few files together, and found that the one Batch object in Fedora had no titles and no creators assigned. Can someone else verify this? Now I'm wondering how we ever used these fields, and why they are no longer used. (Did my batch update job misfire?) I think we should first get to the bottom of how we're currently using these fields in Sufia 6.x, and that will help determine what we do, per @hectorcorrea's suggestion.

**Comment by jcoyne** [comment]
@mjgiarlo I'm not sure the values on the batch form are ever persisted on the UploadSet object, I think they're just pushed on the ActiveJob queue.

**Comment by mjgiarlo** [comment]
@jcoyne It's kinda weird, though has never been problematic, that Batches don't have depositor metadata applied -- I'm guessing this changed in the move to Fedora 4. Anyone can theoretically update anyone else's batches if they know the ID. Maybe?

**Comment by jcoyne** [comment]
Yes, very odd. Why does it need a depositor?  BatchUpdateJob in sufia didn't have one.
It didn't have one here on July 15: https://github.com/projecthydra-labs/sufia-core/blob/e478eb243b06cae8f9745352af927263f4bdefdd/sufia-models/app/jobs/batch_update_job.rb

But it gets added here Sept 1:
https://github.com/projecthydra-labs/curation_concerns/commit/028ce852d822757e10cc5146a6b3d4ce9efd615f#diff-9fdbaa18c2ecca75982f0fba20bd06d9R31

So, it looks to me like that job isn't well tested.  I suspect we could get by using creator, but we ought to make sure that creator gets set somewhere. Presently, the UploadSet gets created here, but creator is never set: https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/actors/curation_concerns/file_set_actor.rb#L34

**Comment by awead** [comment]
@mjgiarlo Verified. No creator is set in a batch in Sufia. I'm looking at 6.4. If an UploadSet is to have no descriptive metadata, why is there creator and title? I can agree with depositor being there, but use the marc relator predicate, and don't call it a creator :smile:.

**Comment by hectorcorrea** [comment]
Let's see if I understand this:

* We do not need neither a `creator` nor a `depositor` in the `UploadSet` metadata. 
* The form will remain with a `creator` but that's not part of the `UploadSet` itself but rather the form value will be used for objects in the `UploadSet`. 

Is that right?

**Comment by hectorcorrea** [comment]
Re-reading @awead comment. We do need a `depositor`. Right?

**Comment by jcoyne** [comment]
I think we either need depositor or creator, but I don't think there's a reason for both.  Maybe you could check SS, but I don't think that either are used presently.

**Comment by awead** [comment]
I would argue either nothing, or just depositor.

**Comment by awead** [comment]
@jcoyne I just checked SS, and in production, out of 2285 batches, there are no titles or creators.

**Comment by hectorcorrea** [comment]
Thanks Adam. I'll remove the both then. I think it will be fairly easy to add one of them back later if we need to and that way we don't bring forward unnecessary baggage.

**Comment by jcoyne** [comment]
If we remove both, then we also must remove the after_batch_update_success, and after_batch_update_failure hooks. Is everyone okay with that (I am) :question:

**Comment by awead** [comment]
:+1: but I'd wait for @mjgiarlo to weigh in.

**Comment by hectorcorrea** [comment]
In the meantime I've updated PR https://github.com/projecthydra-labs/curation_concerns/pull/471 with the changes suggested so far.

**Comment by mjgiarlo** [comment]
Buh. Here's where I am now:

* UploadSets do not need a creator
* (They don't need a title either, I'm thinking, but perhaps that's another ticket?)
* UploadSets should have a depositor property
  * Feel free to use the MARCRelator term for that
  * I'm thinking we should also use apply_depositor_metadata when UploadSets are created to make sure that the depositor property is used, and used in a way consistent to FileSet.depositor.

@jcoyne @hectorcorrea @awead How does that sound?

**Comment by awead** [comment]
@mjgiarlo :+1:

**Comment by mjgiarlo** [comment]
FWIW, I believe @jcoyne objected to applying depositor metadata to the UploadSet, since it will create many new WebAC repository objects (one per UploadSet).

**Comment by jcoyne** [comment]
Upload sets don't exist anymore. Closing.
