### ISSUE TITLE
Refactor Pending and Commented Controller Specs

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#48]
* [ ] spec/controllers/curation_concerns/generic_files_controller_spec.rb
 * [ ] spec/controllers/leases_controller_spec.rb
 * [ ] spec/controllers/catalog_controller_spec.rb
 * [ ] spec/controllers/embargoes_controller_spec.rb

**Comment by escowles** [comment]
PR #130 fixes 7 of 12 issues I found.

The remaining issues are:
1. Two issues with the leases/embargoes not having a show page
2. Two issues with characterization in spec/controllers/curation_concerns/generic_files_controller_spec.rb that say Hydra::Works will handle it (see https://github.com/projecthydra-labs/hydra-works/issues/89)
3. A pending test that's just a wishlist

I can keep looking at 1, but 2 seems out of scope and 3 should probably just be deleted, IMHO.

**Comment by escowles** [comment]
The lease/embargo tests turned out to be a simple fix too: adding show routes for leases/embargoes fixed them.  I also improved the characterization tests with notes about projecthydra-labs/hydra-works#89:

PR https://github.com/projecthydra-labs/curation_concerns/pull/131

**Comment by jpstroop** [comment]
@escowles does it make sense to close this issue at this point and make a couple of new, more specific ones?

**Comment by escowles** [comment]
@jpstroop Yes, I'll close this and create a new issue for the two outstanding issues that are pending projecthydra-labs/hydra-works#89.
