### ISSUE TITLE
FileSetActor.create_content blows up with a local file

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra-labs/curation_concerns#483]
Methods `FileSetActor.create_content` and `FileSetActor.copy_file_to_working_directory` work only when the file passed is an UploadedFile, but throw errors when the file passed is a plain Ruby File object. See https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/actors/curation_concerns/file_set_actor.rb#L50-L59 

Both of these methods expects properties not found in a regular File object, in particular `original_filename`, and `content_type`.

This is not detected in the current test suite because (1) we are only testing with a `Rack::Test::UploadedFile` and (2) the double used in `ingest_local_file_job_spec.rb` is masking the problem.

**Comment by jcoyne** [comment]
@hectorcorrea Colin is already taking care of this in #460
