### ISSUE TITLE
Refactor Pending and Commented Job Specs

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#50]
* [x] spec/jobs/import_url_job_spec.rb
 * [x] spec/jobs/audit_job_spec.rb
 * [x] spec/jobs/characterize_job_spec.rb
 * [x] ~~spec/jobs/batch_update_job_spec.rb~~ (moved to sufia-core)
 * [x] spec/jobs/ingest_local_file_job_spec.rb

**Comment by eliotjordan** [comment]
spec/jobs/characterize_job_spec.rb is done but waiting on #61

**Comment by eliotjordan** [comment]
spec/jobs/ingest_local_file_job_spec.rb is done but waiting on #61
