### ISSUE TITLE
Visibility badge on the show page should have translatable text and title

### ISSUE THREAD

**Issue by barmintor** [projecthydra-labs/curation_concerns#509]
See also: https://github.com/projecthydra/sufia/blob/c40189ecfbc96affa66f654c1f13997c46bc9522/spec/views/generic_file/show.html.erb_spec.rb#L289-L297

Prerequisite for https://github.com/projecthydra-labs/sufia-core/issues/166

**Comment by barmintor** [comment]
@jcoyne should https://github.com/projecthydra-labs/sufia-core/blob/master/app/views/curation_concerns/file_sets/_visibility.html.erb be ported wholesale to this library? Shold it be moved to base, or remain in file_sets?

**Comment by jcoyne** [comment]
@barmintor mostly I was thinking that we should be using i18n keys like `sufia.visibility.private_title_attr` in here https://github.com/projecthydra-labs/curation_concerns/blob/master/app/helpers/curation_concerns/ability_helper.rb#L29-L43

**Comment by barmintor** [comment]
Excellent, thanks for the clarification.

**Comment by jcoyne** [comment]
Once that is done hopefully we could be rid of `render_visibility_badge` https://github.com/projecthydra-labs/sufia-core/blob/master/app/helpers/file_set_helper.rb#L44 in Sufia and just use `visibility_badge` in CurationConcerns.
