### ISSUE TITLE
Add schema.org tags to CurationConcerns::AttributeRenderer

### ISSUE THREAD

**Issue by barmintor** [projecthydra-labs/curation_concerns#512]
CurationConcerns::AttributeRenderer or a subclass should have configurable insertion of schema.org microdata into show views.

**Comment by barmintor** [comment]
@jcoyne @mjgiarlo I assume that something along these lines is preferable to copying the bespoke records/show_fields/FIELD_NAME partials, but we can change/close this ticket if that is not true.

**Comment by jcoyne** [comment]
Yeah, this sounds great.

**Comment by barmintor** [comment]
Required for https://github.com/projecthydra-labs/sufia-core/issues/165

**Comment by barmintor** [comment]
Tracking WIP at https://github.com/projecthydra-labs/curation_concerns/pull/515

**Comment by barmintor** [comment]
I think that branch will be ready to go when I supplement the view test with some unit testing of the new mixin.

**Comment by mjgiarlo** [comment]
:clap:
