### ISSUE TITLE
Adding a file creates an embargo and lease that are not requested

### ISSUE THREAD

**Issue by escowles** [projecthydra-labs/curation_concerns#54]
When I run the [add_file feature test](https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/features/add_file_spec.rb), it creates a Work and GenericFile as expected.  But it also creates a lease and an embargo for both of them.  The Work lease/embargo are blank, but the GenericFile lease/embargo are populated.

**Comment by escowles** [comment]
A summary of the requests made and the objects created by this test: https://gist.github.com/escowles/e46febfd40120231a3c3

**Comment by escowles** [comment]
@jcoyne I think the embargo is actually coming from the FactoryGirl config: https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/factories/generic_works.rb#L5

So maybe this ticket should really be to only set the embargo_date when we're testing embargoes.

**Comment by flyingzumwalt** [comment]
I don't understand the problem.  Pull Requests welcome.

**Comment by jcoyne** [comment]
@flyingzumwalt Embargo in Hydra 9+ is a first class object, so it means more API calls (read worse performance) when it's used.

**Comment by escowles** [comment]
In my tests, about 37% of a ~20 sec test was interacting with the Embargo objects.  So if this is happening everywhere, it could be a huge performance impact.

**Comment by flyingzumwalt** [comment]
:+1:

**Comment by flyingzumwalt** [comment]
I'll add this change to the work I'm doing right now.

**Comment by escowles** [comment]
I'm still seeing a Lease and an Embargo created for each GenericWork and GenericFile created.  When I run [another test that uploads files](https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/actors/curation_concerns/generic_work_actor_spec.rb#L122) (this is the slowest test when I run the test suite), I see the same thing: extra Lease and Embargo objects being created.  The other strange thing I see in that second test is that there are duplicates of the Permission objects for the first file, but not for the second file (even though they are literally the same file object).
