### ISSUE TITLE
Exporting formats of Works

### ISSUE THREAD

**Issue by awead** [projecthydra-labs/curation_concerns#551]
This question was raised for Sufia projecthydra/sufia#1420 and the answer was that export format such as Endnote should reside on the work and not the file set. However, curation concerns puts the method to respond to additional formats on the file set and not the work. Sufia can solve the issue by adding the same method to its works controller, but should we add the method here as well?

Follow up, should it only be on works, or both?

**Comment by jcoyne** [comment]
Yes, move it to works :+1:

**Comment by jcoyne** [comment]
Ugh. I was mistaken. It should be on works and files.
