### ISSUE TITLE
Collection should be assigned in Actor#create_metadata

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/curation_concerns#557]
_From @jcoyne on September 8, 2015 17:12_

Rather than Actor#create_content as the content is just the bitstream, where the metadata is the GenericFile properties.

See https://github.com/projecthydra/sufia/pull/1307#issuecomment-137891935

_Copied from original issue: projecthydra/sufia#1311_

**Comment by mjgiarlo** [comment]
Actors are no longer defined in Sufia. Pls move to CC if it's still relevant.

**Comment by jcoyne** [comment]
Won't fix.
