### ISSUE TITLE
Rename file_presenters/file_presenter_class?

### ISSUE THREAD

**Issue by escowles** [projecthydra-labs/curation_concerns#564]
In WorkShowPresenter, there are methods for accessing the member file presenters and setting the class to use for them:

https://github.com/projecthydra-labs/curation_concerns/blob/master/app/presenters/curation_concerns/work_show_presenter.rb#L27
https://github.com/projecthydra-labs/curation_concerns/blob/master/app/presenters/curation_concerns/work_show_presenter.rb#L42

Since a Work can contain other works, should we rename these methods to `member_presenters` and `member_presenter_class`?

**Comment by jcoyne** [comment]
I think it depends on how you want to display the UI. Would child works be presented as the files are now? Do they conform to the same interface? I suspect they don't, but please show me that my assumption is false.

**Comment by grosscol** [comment]
@escowles I think that is a good point.  At this point, we haven't built to accomodate works -> works -> FileSets.  I agree with @jcoyne that we probably shouldn't stuff the member works into the same presenter interface as the member file sets presenter.

Might be a UI redesign to implement a common presenter for member works & filesets?  Or an additional space for member works?

**Comment by jcoyne** [comment]
@escowles is this complete?
