### ISSUE TITLE
Add filename to upload error

### ISSUE THREAD

**Issue by awead** [projecthydra-labs/curation_concerns#582]
When a file fails to upload, ensure that the json error reports the name of the file along with the error.
See: https://github.com/projecthydra-labs/curation_concerns/blob/5527443e85bfaa115de4cd81d028e75124d62795/app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb#L210

**Comment by mjgiarlo** [comment]
See the full Sufia PR here: https://github.com/projecthydra/sufia/pull/1509

**Comment by mjgiarlo** [comment]
Thanks, @awead!
