### ISSUE TITLE
Cut next release (with Blacklight 6 support)

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/curation_concerns#592]
Pretty please? I'd like this to be in Sufia 7.

(And for bonus points, remove all the crufty tags that point to old Sufia work so that it's easier to see bona fide tags.)

**Comment by jcoyne** [comment]
Blocked by:
- [ ] https://github.com/projecthydra-labs/curation_concerns/pull/591
- [ ] https://github.com/projecthydra-labs/curation_concerns/pull/590
- [ ] https://github.com/projecthydra-labs/curation_concerns/pull/589

**Comment by mjgiarlo** [comment]
#591 is now merged. #590 and #589 are :japanese_ogre: on Travis.

**Comment by jcoyne** [comment]
Fixed in https://github.com/projecthydra-labs/curation_concerns/commit/a65fa566199c59616fd2805c0e0f316e61594e8a
