### ISSUE TITLE
After installation using fcrepo4-exts/fcrepo4-vagrant upload newspaper fails.

### ISSUE THREAD

**Issue by ravn** [projecthydra-labs/curation_concerns#596]
We are investigating "curation_concerns" and have created a minimal Rails project using the instructions on the web page.  For SOLR and Fedora we have https://github.com/fcrepo4-exts/fcrepo4-vagrant running in a vagrant box on the same machine, and adjusted the SOLR and Fedora URL's in the config file.

localhost:3000 gives the front page and after logging in I can choose "+" - "Add newspaper" to go to http://localhost:3000/concern/newspapers/new. I fill out the form and attach a 30ish MB PDF, and click Create Newspaper, which results in an error page:

RSolr::Error::Http - 400 Bad Request Error: {'responseHeader'=>{'status'=>400,'QTime'=>2,'params'=>{'q'=>'{!join from=proxy_in_ssi to=id}ordered_targets_ssim:g732d8963','qt'=>'standard','wt'=>'ruby'}},'error'=>{'msg'=>'undefined field ordered_targets_ssim','code'=>400}} URI: http://localhost:8080/solr/select?wt=ruby&q=%7B%21join+from%3Dproxy_in_ssi+to%3Did%7Dordered_targets_ssim%3Ag732d8963&qt=standard Backtrace: /var/lib/gems/2.1.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response' /var/lib/gems/2.1.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute' /var/lib/gems/2.1.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive' (eval):2:in `get' /var/lib/gems/2.1.0/gems/active-fedora-9.7.0/lib/active_fedora/solr_service.rb:107:in `query' /var/lib/gems/2.1.0/gems/activefedora-aggregation-0.8.1/lib/active_fedora/aggregation/base_extension.rb:27:in `ordered_by_ids' /var/lib/gems/2.1.0/gems/activefedora-aggregation-0.8.1/lib/active_fedora/aggregation/base_extension.rb:20:in `ordered_by' /var/lib/gems/2.1.0/gems/hydra-pcdm-0.3.2/lib/hydra/pcdm/models/concerns/object_behavior.rb:43:in `in_objects' /var/lib/gems/2.1.0/gems/curation_concerns-models-0.6.0/app/models/concerns/curation_concerns/file_set/belongs_to_works.rb:11:in `generic_works' /var/lib/gems/2.1.0/gems/curation_concerns-models-0.6.0/app/models/concerns/curation_concerns/file_set/belongs_to_works.rb:16:in `generic_work_ids' /var/lib/gems/2.1.0/gems/curation_concerns-models-0.6.0/app/indexers/curation_concerns/file_set_indexer.rb:17:in `block in generate_solr_document'

(http://localhost:8080/solr/select?wt=ruby&q=%7B%21join+from%3Dproxy_in_ssi+to%3Did%7Dordered_targets_ssim%3Adn39x152w&qt=standard gives 

{'responseHeader'=>{'status'=>400,'QTime'=>2,'params'=>{'q'=>'{!join from=proxy_in_ssi to=id}ordered_targets_ssim:dn39x152w','qt'=>'standard','wt'=>'ruby'}},'error'=>{'msg'=>'undefined field ordered_targets_ssim','code'=>400}}
)

It appears that SOLR dislikes the ordered_targets_ssim field.  

Have I missed a step somewhere?

**Comment by jcoyne** [comment]
Yes, it looks like your solr isn't using the default Hydra solr schema:
https://github.com/projecthydra/active_fedora/blob/master/lib/generators/active_fedora/config/solr/templates/solr_conf/conf/schema.xml

-Justin
