### ISSUE TITLE
Support AF 9.8.x (w/ Solr 5 & FCR 4.5)

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/curation_concerns#604]
Because the build is broken.

I've already started working on this, but I wanted to ticketize this so I don't forget. ;)

**Comment by mjgiarlo** [comment]
Work started here:

https://github.com/projecthydra-labs/curation_concerns/commit/4acf83d5b1ffe3018ecb4fd94281843fdc6788e7

Currently there's lots of fail that looks like:

`Faraday::ConnectionFailed: Connection refused - connect(2) for localhost port 8986`

**Comment by mjgiarlo** [comment]
Sounds like @jcoyne has picked this up. re-assigning!

**Comment by grosscol** [comment]
Looks like this is all set?

**Comment by jcoyne** [comment]
Fixed by #605
