### ISSUE TITLE
Collection titles are displaying incorrectly

### ISSUE THREAD

**Issue by mark-dce** [projecthydra-labs/curation_concerns#613]
When I create a new collection with curation_concerns and go to the collection view (/collections/[:id]), the view is showing the containing array instead of a list of titles or a single title.

In the screenshot below, I want to see
> UCSB Electronic Theses and Dissertations

instead of  

> ["UCSB Electronic Theses and Dissertations"]

<img width="743" alt="collection_concerns - collection titiles" src="https://cloud.githubusercontent.com/assets/3064318/12992057/e572ba3a-d0d7-11e5-9765-082001ab8255.png">

**Comment by jcoyne** [comment]
I think this is due to metadata changes in  hydra-collections  7.0

**Comment by tpendragon** [comment]
@jcoyne Is there a timeline for this issue?

**Comment by jcoyne** [comment]
This was due to overrides in alexandria, not a CC issue.
