### ISSUE TITLE
Replace references to $redis with Redis.current, prefer Redis.current to Resque.redis

### ISSUE THREAD

**Issue by barmintor** [projecthydra-labs/curation_concerns#639]
https://github.com/projecthydra-labs/curation_concerns/blob/64eab4d87fac8b88367ebb5e34b4d34ad7ce6716/curation_concerns-models/lib/generators/curation_concerns/models/templates/config/redis_config.rb
https://github.com/projecthydra-labs/curation_concerns/blob/64eab4d87fac8b88367ebb5e34b4d34ad7ce6716/curation_concerns-models/lib/generators/curation_concerns/models/templates/config/resque_config.rb

**Comment by cam156** [comment]
@mjgiarlo we currently only have one redis server installed on our servers.  I believe the activity streams use redis, and resque uses redis.   I an not really up on the difference between the two redis connections.  The ones referenced here seem to be the  resque ones.

**Comment by mjgiarlo** [comment]
@cam156 There was a time when we used local Redis instances for Resque jobs and a shared instance for activity streams, which led to [a change in the Redis config](https://github.com/psu-stewardship/scholarsphere/blob/develop/config/redis.yml.sample#L7-L12) and [customization of the Resque initializer](https://github.com/psu-stewardship/scholarsphere/blob/5eea37b92388fbebc9a1339f184cc6142ac52e1f/config/initializers/resque_config.rb#L4). Maybe y'all don't need this anymore though?
