### ISSUE TITLE
when clamAV is disabled then `file_has_virus?`=> true, validation fails

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#789]
Validation should not fail if ClamAV is not installed.

**Comment by jeremyf** [comment]
What is the expected behavior in production if ClamAV is not installed?

**Comment by jcoyne** [comment]
Previously (in Sufia) the presence of ClamAV meant "do virus check" and the absence indicated "Don't check for viruses."  This is probably too arcane and ought to be moved to config.

**Comment by awead** [comment]
See: projecthydra-labs/hydra-works#297

**Comment by mjgiarlo** [comment]
projecthydra-labs/hydra-works#297 has now been merged.

**Comment by mjgiarlo** [comment]
Hydra-works 0.11.0 has been released with this change.
