### ISSUE TITLE
Confirm that Collections are actually PCDM collections

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#86]
i.e. Are we using the interfaces provided by `Hydra::PCDM::Collection`?

**Comment by escowles** [comment]
I wrote a quick test to demonstrate that the Hydra::PCDM::Collection API works on instances that include CurationConcerns::CollectionBehavior.  But looking at the description, I think that's not what this ticket is about.  Is the task to verify that we're actually using the Hydra::PCDM::Collection API -- e.g., mocking out the members instance, calling CollectionBehavior#add_member, and verifying that the member was added to members?

**Comment by jpstroop** [comment]
Sorry to leave this hanging. I wrote this issue in haste after remembering how we thought we had `GenericWork` working for several days and then realized that we weren't including `Hydra::Works::GenericWorkBehavior` (or something like that...maybe it was at a lower level). So that's what needs to be checked: Collections are presumably behaving according to all of CurationConcerns' assumptions about what they should do, but are they persisted to Fedora as PCDM Collections? It sounds like this is the case based on the spec you wrote?

**Comment by escowles** [comment]
@jpstroop OK, that makes sense -- I remember that being mentioned.  So I think https://github.com/projecthydra-labs/curation_concerns/pull/137 is good to prevent that: it checks the RDF types and that the underlying interface methods work.

**Comment by jpstroop** [comment]
Great, thanks!
